apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: alice
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090'] # Prometheus service address

      - job_name: 'pod'
        scrape_interval: 5s
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
              - {{.NAMESPACE}} # modify here to your own namespace

        relabel_configs:
          # only scrape kuscia pod which has kuscia.secretflow/should_be_scraped=true annotation
          - source_labels: [__meta_kubernetes_pod_annotation_kuscia_secretflow_should_be_scraped]
            action: keep
            regex: true

          # scrape kuscia pod which has kuscia.secretflow/metric_path annotation as the metric path
          - source_labels: [__meta_kubernetes_pod_annotation_kuscia_secretflow_metric_path]
            action: replace
            target_label: __metrics_path__

          # scrape kuscia pod which has kuscia.secretflow/metric_port annotation as the metric port
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_kuscia_secretflow_metric_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: pod_ip
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_kuscia_secretflow_kd_name]
            action: replace
            target_label: kuscia_deployment_name