apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-kuscia
  namespace: alice
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-kuscia
  namespace: alice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-kuscia
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitor
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
  annotations:
    kubernetes.io/service-account.name: prometheus
type: kubernetes.io/service-account-token