apiVersion: kuscia.secretflow/v1alpha1
kind: AppImage
metadata:
  name: {{APP_IMAGE_NAME}}
spec:
  configTemplates:
    task-config.conf: |
      {
        "task_id": "{{.TASK_ID}}",
        "task_input_config": "{{.TASK_INPUT_CONFIG}}",
        "task_cluster_def": "{{.TASK_CLUSTER_DEFINE}}",
        "allocated_ports": "{{.ALLOCATED_PORTS}}"
      }
  deployTemplates:
    - name: secretflow
      replicas: 1
      spec:
        containers:
          - command:
              - sh
            args:
              - -c
              - python -m secretflow.kuscia.entry /etc/kuscia/task-config.conf
            configVolumeMounts:
              - mountPath: /etc/kuscia/task-config.conf
                subPath: task-config.conf
            name: secretflow
            ports:
              - name: spu
                protocol: GRPC
                scope: Cluster
              - name: fed
                protocol: GRPC
                scope: Cluster
              - name: global
                protocol: GRPC
                scope: Domain
              - name: node-manager
                protocol: GRPC
                scope: Local
              - name: object-manager
                protocol: GRPC
                scope: Local
              - name: client-server
                protocol: GRPC
                scope: Local
              - name: inference
                protocol: HTTP
                scope: Cluster
            # metricProbe:
            #   httpGet:
            #     path: /metrics
            #     port: {{.METRIC_PORT}} 
            workingDir: /work
        restartPolicy: Never
  image:
    id: abc
    name: {{IMAGE_NAME}}
    sign: abc
    tag: {{IMAGE_TAG}}
