// Copyright 2025 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: kuscia/proto/api/v1alpha1/diagnose/envoylog.proto

package diagnose

import (
	v1alpha1 "github.com/secretflow/kuscia/proto/api/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvoyLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId     string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CreateTime string `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	DomainId   string `protobuf:"bytes,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
}

func (x *EnvoyLogRequest) Reset() {
	*x = EnvoyLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvoyLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvoyLogRequest) ProtoMessage() {}

func (x *EnvoyLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvoyLogRequest.ProtoReflect.Descriptor instead.
func (*EnvoyLogRequest) Descriptor() ([]byte, []int) {
	return file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescGZIP(), []int{0}
}

func (x *EnvoyLogRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *EnvoyLogRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *EnvoyLogRequest) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

type EnvoyLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip            string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Timestamp     string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeName      string `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ServiceName   string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InterfaceAddr string `protobuf:"bytes,5,opt,name=interface_addr,json=interfaceAddr,proto3" json:"interface_addr,omitempty"`
	HttpMethod    string `protobuf:"bytes,6,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	TraceId       string `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	StatusCode    string `protobuf:"bytes,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ContentLength string `protobuf:"bytes,9,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	RequestTime   string `protobuf:"bytes,10,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`
}

func (x *EnvoyLog) Reset() {
	*x = EnvoyLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvoyLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvoyLog) ProtoMessage() {}

func (x *EnvoyLog) ProtoReflect() protoreflect.Message {
	mi := &file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvoyLog.ProtoReflect.Descriptor instead.
func (*EnvoyLog) Descriptor() ([]byte, []int) {
	return file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescGZIP(), []int{1}
}

func (x *EnvoyLog) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *EnvoyLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *EnvoyLog) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EnvoyLog) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *EnvoyLog) GetInterfaceAddr() string {
	if x != nil {
		return x.InterfaceAddr
	}
	return ""
}

func (x *EnvoyLog) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *EnvoyLog) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *EnvoyLog) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *EnvoyLog) GetContentLength() string {
	if x != nil {
		return x.ContentLength
	}
	return ""
}

func (x *EnvoyLog) GetRequestTime() string {
	if x != nil {
		return x.RequestTime
	}
	return ""
}

type EnvoyLogInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvoyLogList []*EnvoyLog `protobuf:"bytes,1,rep,name=envoy_log_list,json=envoyLogList,proto3" json:"envoy_log_list,omitempty"`
	Type         string      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *EnvoyLogInfo) Reset() {
	*x = EnvoyLogInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvoyLogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvoyLogInfo) ProtoMessage() {}

func (x *EnvoyLogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvoyLogInfo.ProtoReflect.Descriptor instead.
func (*EnvoyLogInfo) Descriptor() ([]byte, []int) {
	return file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescGZIP(), []int{2}
}

func (x *EnvoyLogInfo) GetEnvoyLogList() []*EnvoyLog {
	if x != nil {
		return x.EnvoyLogList
	}
	return nil
}

func (x *EnvoyLogInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type EnvoyLogInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        *v1alpha1.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EnvoyInfoList []*EnvoyLogInfo  `protobuf:"bytes,2,rep,name=envoy_info_list,json=envoyInfoList,proto3" json:"envoy_info_list,omitempty"`
	DomainId      string           `protobuf:"bytes,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
}

func (x *EnvoyLogInfoResponse) Reset() {
	*x = EnvoyLogInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvoyLogInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvoyLogInfoResponse) ProtoMessage() {}

func (x *EnvoyLogInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvoyLogInfoResponse.ProtoReflect.Descriptor instead.
func (*EnvoyLogInfoResponse) Descriptor() ([]byte, []int) {
	return file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescGZIP(), []int{3}
}

func (x *EnvoyLogInfoResponse) GetStatus() *v1alpha1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *EnvoyLogInfoResponse) GetEnvoyInfoList() []*EnvoyLogInfo {
	if x != nil {
		return x.EnvoyInfoList
	}
	return nil
}

func (x *EnvoyLogInfoResponse) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

var File_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto protoreflect.FileDescriptor

var file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDesc = []byte{
	0x0a, 0x31, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x64, 0x69, 0x61, 0x67,
	0x6e, 0x6f, 0x73, 0x65, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x22, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x64,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x65, 0x1a, 0x26, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x68, 0x0a, 0x0f, 0x45, 0x6e, 0x76, 0x6f, 0x79, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0xc6, 0x02, 0x0a, 0x08, 0x45, 0x6e,
	0x76, 0x6f, 0x79, 0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x68,
	0x74, 0x74, 0x70, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x68, 0x74, 0x74, 0x70, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x76, 0x0a, 0x0c, 0x45, 0x6e, 0x76, 0x6f, 0x79, 0x4c, 0x6f, 0x67, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x52, 0x0a, 0x0e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6b, 0x75, 0x73,
	0x63, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x65, 0x2e,
	0x45, 0x6e, 0x76, 0x6f, 0x79, 0x4c, 0x6f, 0x67, 0x52, 0x0c, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x4c,
	0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x14, 0x45,
	0x6e, 0x76, 0x6f, 0x79, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x58,
	0x0a, 0x0f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x76,
	0x6f, 0x79, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x65, 0x6e, 0x76, 0x6f, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x6b,
	0x75, 0x73, 0x63, 0x69, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescOnce sync.Once
	file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescData = file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDesc
)

func file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescGZIP() []byte {
	file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescOnce.Do(func() {
		file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescData = protoimpl.X.CompressGZIP(file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescData)
	})
	return file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDescData
}

var file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_goTypes = []interface{}{
	(*EnvoyLogRequest)(nil),      // 0: kuscia.proto.api.v1alpha1.diagnose.EnvoyLogRequest
	(*EnvoyLog)(nil),             // 1: kuscia.proto.api.v1alpha1.diagnose.EnvoyLog
	(*EnvoyLogInfo)(nil),         // 2: kuscia.proto.api.v1alpha1.diagnose.EnvoyLogInfo
	(*EnvoyLogInfoResponse)(nil), // 3: kuscia.proto.api.v1alpha1.diagnose.EnvoyLogInfoResponse
	(*v1alpha1.Status)(nil),      // 4: kuscia.proto.api.v1alpha1.Status
}
var file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_depIdxs = []int32{
	1, // 0: kuscia.proto.api.v1alpha1.diagnose.EnvoyLogInfo.envoy_log_list:type_name -> kuscia.proto.api.v1alpha1.diagnose.EnvoyLog
	4, // 1: kuscia.proto.api.v1alpha1.diagnose.EnvoyLogInfoResponse.status:type_name -> kuscia.proto.api.v1alpha1.Status
	2, // 2: kuscia.proto.api.v1alpha1.diagnose.EnvoyLogInfoResponse.envoy_info_list:type_name -> kuscia.proto.api.v1alpha1.diagnose.EnvoyLogInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_init() }
func file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_init() {
	if File_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvoyLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvoyLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvoyLogInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvoyLogInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_goTypes,
		DependencyIndexes: file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_depIdxs,
		MessageInfos:      file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_msgTypes,
	}.Build()
	File_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto = out.File
	file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_rawDesc = nil
	file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_goTypes = nil
	file_kuscia_proto_api_v1alpha1_diagnose_envoylog_proto_depIdxs = nil
}
