apiVersion: kuscia.secretflow/v1alpha1
kind: AppImage
metadata:
  name: diagnose-image
spec:
  configTemplates:
    task-config.conf: |
      {
        "task_input_config": "{{.TASK_INPUT_CONFIG}}",
        "server_port": {{{.ALLOCATED_PORTS.ports[0].port}}},
        "domains": ["{{{.TASK_CLUSTER_DEFINE.parties[0].name}}}", "{{{.TASK_CLUSTER_DEFINE.parties[1].name}}}"],
        "endpoints": ["{{{.TASK_CLUSTER_DEFINE.parties[0].services[0].endpoints[0]}}}", "{{{.TASK_CLUSTER_DEFINE.parties[1].services[0].endpoints[0]}}}"],
        "self_index": {{{.TASK_CLUSTER_DEFINE.selfPartyIdx}}}
      }
  deployTemplates:
    - name: diagnose
      replicas: 1
      spec:
        containers:
          - command:
              - sh
            args:
              - -c
              - /home/kuscia/bin/kuscia diagnose app -c /etc/kuscia/task-config.conf
            configVolumeMounts:
              - mountPath: /etc/kuscia/task-config.conf
                subPath: task-config.conf
            name: diagnose
            ports:
              - name: test-server
                port: 20005
                protocol: HTTP
                scope: Cluster
            workingDir: /root
        restartPolicy: Never
  image:
    name: {{.IMAGE_NAME}}
    tag: {{.IMAGE_TAG}}