apiVersion: kuscia.secretflow/v1alpha1
kind: AppImage
metadata:
  name: secretflow-image
spec:
  configTemplates:
    task-config.conf: |
      {
        "task_id": "{{.TASK_ID}}",
        "task_input_config": "{{.TASK_INPUT_CONFIG}}",
        "task_cluster_def": "{{.TASK_CLUSTER_DEFINE}}",
        "allocated_ports": "{{.ALLOCATED_PORTS}}"
      }
  deployTemplates:
    - name: secretflow
      replicas: 1
      spec:
        containers:
          - command:
              - sh
            args:
              - -c
              - "python -m secretflow.kuscia.entry /etc/kuscia/task-config.conf"
            configVolumeMounts:
              - mountPath: /etc/kuscia/task-config.conf
                subPath: task-config.conf
            name: secretflow
            ports:
              - name: spu
                port: 54509
                protocol: GRPC
                scope: Cluster
              - name: fed
                port: 8080
                protocol: GRPC
                scope: Cluster
              - name: global
                port: 8081
                protocol: GRPC
                scope: Domain
            workingDir: /work
        restartPolicy: Never
  image:
    id: abc
    name: secretflow/secretflow-lite-anolis8
    sign: abc
    tag: "0.8.3b0"
---
apiVersion: kuscia.secretflow/v1alpha1
kind: AppImage
metadata:
  name: secretflow-nsjail-image
spec:
  configTemplates:
    task-config.conf: |
      {
        "task_id": "{{.TASK_ID}}",
        "task_input_config": "{{.TASK_INPUT_CONFIG}}",
        "task_cluster_def": "{{.TASK_CLUSTER_DEFINE}}",
        "allocated_ports": "{{.ALLOCATED_PORTS}}"
      }
  deployTemplates:
    - name: secretflow
      replicas: 1
      spec:
        containers:
          - command:
              - sh
            args:
              - -c
              - "sh .nsjail/run.sh"
            configVolumeMounts:
              - mountPath: /etc/kuscia/task-config.conf
                subPath: task-config.conf
            name: secretflow
            ports:
              - name: spu
                port: 54509
                protocol: GRPC
                scope: Cluster
              - name: fed
                port: 8080
                protocol: GRPC
                scope: Cluster
              - name: global
                port: 8081
                protocol: GRPC
                scope: Domain
            workingDir: /root
            securityContext:
              privileged: true
        restartPolicy: Never
  image:
    id: abc
    name: secretflow/secretflow-lite-anolis8
    sign: abc
    tag: "0.8.3b0"