apiVersion: kuscia.secretflow/v1alpha1
kind: ClusterDomainRoute
metadata:
  name: {{.SRC_DOMAIN}}-{{.DEST_DOMAIN}}
spec:
  source: {{.SRC_DOMAIN}}
  destination: {{.DEST_DOMAIN}}
  interConnProtocol: kuscia
  endpoint:
    host: {{.HOST}}
    ports:
      - name: http
        protocol: HTTP
        pathPrefix: {{.PATH}}
        isTLS: {{.ISTLS}}
        port: {{.PORT}}
  transit:
    transitMethod: THIRD-DOMAIN
    domain:
      domainID: {{.TRANSIT_DOMAIN}}
  bodyEncryption:
   algorithm: AES
  authenticationType: Token
  tokenConfig:
    tokenGenMethod: RSA-GEN
    rollingUpdatePeriod: 86400
  requestHeadersToAdd:
    Authorization: Bearer {{.TOKEN}}