apiVersion: kuscia.secretflow/v1alpha1
kind: ClusterDomainRoute
metadata:
  name: {{.SRC_DOMAIN}}-{{.DEST_DOMAIN}}
spec:
  source: {{.SRC_DOMAIN}}
  destination: {{.DEST_DOMAIN}}
  interConnProtocol: kuscia
  endpoint:
    host: {{.HOST}}
    ports:
      - name: http
        protocol: HTTP
        isTLS: true
        port: {{.PORT}}
  authenticationType: MTLS
  mTLSConfig:
    tlsCA: {{.TLS_CA}}
    sourceClientCert: {{.SRC_CERT}}
