apiVersion: kuscia.secretflow/v1alpha1
kind: ClusterDomainRoute
metadata:
  name: {{.SRC_DOMAIN}}-{{.DEST_DOMAIN}}
spec:
  source: {{.SRC_DOMAIN}}
  destination: {{.DEST_DOMAIN}}
  interConnProtocol: {{.INTERCONN_PROTOCOL}}
  endpoint:
    host: {{.HOST}}
    ports:
      - name: http
        protocol: HTTP
        pathPrefix: {{.PATH}}
        isTLS: {{.ISTLS}}
        port: {{.PORT}}
  authenticationType: Token
  tokenConfig:
    tokenGenMethod: RSA-GEN
    rollingUpdatePeriod: 600
  requestHeadersToAdd:
    Authorization: Bearer {{.TOKEN}}