apiVersion: kuscia.secretflow/v1alpha1
kind: KusciaDeployment
metadata:
  labels:
    kuscia.secretflow/app-type: serving
  name: dataproxy-serving
  namespace: cross-domain
spec:
  initiator: {{.DOMAIN_ID}}
  inputConfig: '{}'
  parties:
    - appImageRef: dataproxy-image
      domainID: {{.DOMAIN_ID}}