{
 "title": "network_center",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "envoy_upstream_cx_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total transmission bytes from upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "envoy_upstream_cx_tx_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total upstream requests",
   "type": "timeseries",
   "description": "The total number of end-to-end requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "envoy_upstream_rq_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total received bytes from  upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "envoy_upstream_cx_rx_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average RTT of a cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "ss_rtt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time-out rate of upstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "envoy_upstream_rq_timeout{}/envoy_upstream_rq_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retransmission rate of a cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    { "expr": "ss_retran_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failure/time-out rate of upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "envoy_upstream_cx_connect_fail{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_upstream_cx_connect_timeout",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total retransmissions of a cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "targets": [
    { "expr": "ss_retrans", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health check failure rate of clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "envoy_health_check__failure{}/envoy_health_check__attempt{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}