apiVersion: v1
kind: Service
metadata:
  name: secretpad
  namespace: {{.DOMAIN}}
spec:
  externalName: {{.SECRET_PAD_CTR_NAME}}
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
  type: ExternalName