# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kuscia/proto/api/v1alpha1/handshake/handshake.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kuscia.proto.api.v1alpha1 import common_pb2 as kuscia_dot_proto_dot_api_dot_v1alpha1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3kuscia/proto/api/v1alpha1/handshake/handshake.proto\x12#kuscia.proto.api.v1alpha1.handshake\x1a&kuscia/proto/api/v1alpha1/common.proto\".\n\x0bTokenConfig\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\x03\"\x91\x01\n\x10HandShakeRequest\x12\x11\n\tdomain_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x46\n\x0ctoken_config\x18\x03 \x01(\x0b\x32\x30.kuscia.proto.api.v1alpha1.handshake.TokenConfig\x12\x14\n\x0crequest_time\x18\x04 \x01(\x03\"/\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_time\x18\x02 \x01(\x03\"\x81\x01\n\x11HandShakeResponse\x12\x31\n\x06status\x18\x01 \x01(\x0b\x32!.kuscia.proto.api.v1alpha1.Status\x12\x39\n\x05token\x18\x02 \x01(\x0b\x32*.kuscia.proto.api.v1alpha1.handshake.Token\"G\n\x0fRegisterRequest\x12\x11\n\tdomain_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63sr\x18\x02 \x01(\t\x12\x14\n\x0crequest_time\x18\x03 \x01(\x03\"S\n\x10RegisterResponse\x12\x31\n\x06status\x18\x01 \x01(\x0b\x32!.kuscia.proto.api.v1alpha1.Status\x12\x0c\n\x04\x63\x65rt\x18\x03 \x01(\tB^\n!com.secretflow.v1alpha1.handshakeZ9github.com/secretflow/kuscia/proto/api/v1alpha1/handshakeb\x06proto3')



_TOKENCONFIG = DESCRIPTOR.message_types_by_name['TokenConfig']
_HANDSHAKEREQUEST = DESCRIPTOR.message_types_by_name['HandShakeRequest']
_TOKEN = DESCRIPTOR.message_types_by_name['Token']
_HANDSHAKERESPONSE = DESCRIPTOR.message_types_by_name['HandShakeResponse']
_REGISTERREQUEST = DESCRIPTOR.message_types_by_name['RegisterRequest']
_REGISTERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterResponse']
TokenConfig = _reflection.GeneratedProtocolMessageType('TokenConfig', (_message.Message,), {
  'DESCRIPTOR' : _TOKENCONFIG,
  '__module__' : 'kuscia.proto.api.v1alpha1.handshake.handshake_pb2'
  # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.handshake.TokenConfig)
  })
_sym_db.RegisterMessage(TokenConfig)

HandShakeRequest = _reflection.GeneratedProtocolMessageType('HandShakeRequest', (_message.Message,), {
  'DESCRIPTOR' : _HANDSHAKEREQUEST,
  '__module__' : 'kuscia.proto.api.v1alpha1.handshake.handshake_pb2'
  # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.handshake.HandShakeRequest)
  })
_sym_db.RegisterMessage(HandShakeRequest)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'kuscia.proto.api.v1alpha1.handshake.handshake_pb2'
  # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.handshake.Token)
  })
_sym_db.RegisterMessage(Token)

HandShakeResponse = _reflection.GeneratedProtocolMessageType('HandShakeResponse', (_message.Message,), {
  'DESCRIPTOR' : _HANDSHAKERESPONSE,
  '__module__' : 'kuscia.proto.api.v1alpha1.handshake.handshake_pb2'
  # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.handshake.HandShakeResponse)
  })
_sym_db.RegisterMessage(HandShakeResponse)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'kuscia.proto.api.v1alpha1.handshake.handshake_pb2'
  # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.handshake.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'kuscia.proto.api.v1alpha1.handshake.handshake_pb2'
  # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.handshake.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!com.secretflow.v1alpha1.handshakeZ9github.com/secretflow/kuscia/proto/api/v1alpha1/handshake'
  _TOKENCONFIG._serialized_start=132
  _TOKENCONFIG._serialized_end=178
  _HANDSHAKEREQUEST._serialized_start=181
  _HANDSHAKEREQUEST._serialized_end=326
  _TOKEN._serialized_start=328
  _TOKEN._serialized_end=375
  _HANDSHAKERESPONSE._serialized_start=378
  _HANDSHAKERESPONSE._serialized_end=507
  _REGISTERREQUEST._serialized_start=509
  _REGISTERREQUEST._serialized_end=580
  _REGISTERRESPONSE._serialized_start=582
  _REGISTERRESPONSE._serialized_end=665
# @@protoc_insertion_point(module_scope)
