name: Consulting issue template
description: Thank you for reporting the issue!
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that you are reporting the consultation issue on GitHub.（Api Usage/Feature/Document/Others）
        Please post on our [discussions](https://github.com/secretflow/kuscia/discussions) instead if you want to ask questions or share ideas.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: false
      options:
        - Api Usage
        - Feature
        - Document
        - Others
    validations:
      required: true
  - type: dropdown
    id: searched-for-existing-issues
    attributes:
      label: Search for existing issues similar to yours
      description: Existing [documents](https://www.secretflow.org.cn/zh-CN/docs/kuscia/main/) and [issues](https://github.com/secretflow/kuscia/issues)
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: kuscia-version
    attributes:
      label: Kuscia Version
      description:
      placeholder: e.g., kuscia 0.7.0b0
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to Relevant Documentation
      description: For faster problem-solving, if there are relevant documents, please attach links.
      placeholder: e.g.,https://www.secretflow.org.cn/zh-CN/docs/kuscia/main/reference/concepts
    validations:
      required: false
  - type: textarea
    id: Question-Details
    attributes:
      label: Question Details
      description: Please provide a detailed description of the problem you have encountered, including the performance of the problem, the difference between expected and actual behavior, and the solutions you have tried. This will help us understand and solve your problem faster.
      placeholder: Describe the questions you want to consult and what you want to do
      value:
      render: shell
    validations:
      required: true
