// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.8
// source: kuscia/proto/api/v1alpha1/kusciaapi/domaindatagrant.proto

package kusciaapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DomainDataGrantService_CreateDomainDataGrant_FullMethodName     = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataGrantService/CreateDomainDataGrant"
	DomainDataGrantService_UpdateDomainDataGrant_FullMethodName     = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataGrantService/UpdateDomainDataGrant"
	DomainDataGrantService_DeleteDomainDataGrant_FullMethodName     = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataGrantService/DeleteDomainDataGrant"
	DomainDataGrantService_QueryDomainDataGrant_FullMethodName      = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataGrantService/QueryDomainDataGrant"
	DomainDataGrantService_BatchQueryDomainDataGrant_FullMethodName = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataGrantService/BatchQueryDomainDataGrant"
	DomainDataGrantService_ListDomainDataGrant_FullMethodName       = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataGrantService/ListDomainDataGrant"
)

// DomainDataGrantServiceClient is the client API for DomainDataGrantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DomainDataGrantServiceClient interface {
	CreateDomainDataGrant(ctx context.Context, in *CreateDomainDataGrantRequest, opts ...grpc.CallOption) (*CreateDomainDataGrantResponse, error)
	UpdateDomainDataGrant(ctx context.Context, in *UpdateDomainDataGrantRequest, opts ...grpc.CallOption) (*UpdateDomainDataGrantResponse, error)
	DeleteDomainDataGrant(ctx context.Context, in *DeleteDomainDataGrantRequest, opts ...grpc.CallOption) (*DeleteDomainDataGrantResponse, error)
	QueryDomainDataGrant(ctx context.Context, in *QueryDomainDataGrantRequest, opts ...grpc.CallOption) (*QueryDomainDataGrantResponse, error)
	BatchQueryDomainDataGrant(ctx context.Context, in *BatchQueryDomainDataGrantRequest, opts ...grpc.CallOption) (*BatchQueryDomainDataGrantResponse, error)
	ListDomainDataGrant(ctx context.Context, in *ListDomainDataGrantRequest, opts ...grpc.CallOption) (*ListDomainDataGrantResponse, error)
}

type domainDataGrantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDomainDataGrantServiceClient(cc grpc.ClientConnInterface) DomainDataGrantServiceClient {
	return &domainDataGrantServiceClient{cc}
}

func (c *domainDataGrantServiceClient) CreateDomainDataGrant(ctx context.Context, in *CreateDomainDataGrantRequest, opts ...grpc.CallOption) (*CreateDomainDataGrantResponse, error) {
	out := new(CreateDomainDataGrantResponse)
	err := c.cc.Invoke(ctx, DomainDataGrantService_CreateDomainDataGrant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataGrantServiceClient) UpdateDomainDataGrant(ctx context.Context, in *UpdateDomainDataGrantRequest, opts ...grpc.CallOption) (*UpdateDomainDataGrantResponse, error) {
	out := new(UpdateDomainDataGrantResponse)
	err := c.cc.Invoke(ctx, DomainDataGrantService_UpdateDomainDataGrant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataGrantServiceClient) DeleteDomainDataGrant(ctx context.Context, in *DeleteDomainDataGrantRequest, opts ...grpc.CallOption) (*DeleteDomainDataGrantResponse, error) {
	out := new(DeleteDomainDataGrantResponse)
	err := c.cc.Invoke(ctx, DomainDataGrantService_DeleteDomainDataGrant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataGrantServiceClient) QueryDomainDataGrant(ctx context.Context, in *QueryDomainDataGrantRequest, opts ...grpc.CallOption) (*QueryDomainDataGrantResponse, error) {
	out := new(QueryDomainDataGrantResponse)
	err := c.cc.Invoke(ctx, DomainDataGrantService_QueryDomainDataGrant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataGrantServiceClient) BatchQueryDomainDataGrant(ctx context.Context, in *BatchQueryDomainDataGrantRequest, opts ...grpc.CallOption) (*BatchQueryDomainDataGrantResponse, error) {
	out := new(BatchQueryDomainDataGrantResponse)
	err := c.cc.Invoke(ctx, DomainDataGrantService_BatchQueryDomainDataGrant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataGrantServiceClient) ListDomainDataGrant(ctx context.Context, in *ListDomainDataGrantRequest, opts ...grpc.CallOption) (*ListDomainDataGrantResponse, error) {
	out := new(ListDomainDataGrantResponse)
	err := c.cc.Invoke(ctx, DomainDataGrantService_ListDomainDataGrant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainDataGrantServiceServer is the server API for DomainDataGrantService service.
// All implementations must embed UnimplementedDomainDataGrantServiceServer
// for forward compatibility
type DomainDataGrantServiceServer interface {
	CreateDomainDataGrant(context.Context, *CreateDomainDataGrantRequest) (*CreateDomainDataGrantResponse, error)
	UpdateDomainDataGrant(context.Context, *UpdateDomainDataGrantRequest) (*UpdateDomainDataGrantResponse, error)
	DeleteDomainDataGrant(context.Context, *DeleteDomainDataGrantRequest) (*DeleteDomainDataGrantResponse, error)
	QueryDomainDataGrant(context.Context, *QueryDomainDataGrantRequest) (*QueryDomainDataGrantResponse, error)
	BatchQueryDomainDataGrant(context.Context, *BatchQueryDomainDataGrantRequest) (*BatchQueryDomainDataGrantResponse, error)
	ListDomainDataGrant(context.Context, *ListDomainDataGrantRequest) (*ListDomainDataGrantResponse, error)
	mustEmbedUnimplementedDomainDataGrantServiceServer()
}

// UnimplementedDomainDataGrantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDomainDataGrantServiceServer struct {
}

func (UnimplementedDomainDataGrantServiceServer) CreateDomainDataGrant(context.Context, *CreateDomainDataGrantRequest) (*CreateDomainDataGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDomainDataGrant not implemented")
}
func (UnimplementedDomainDataGrantServiceServer) UpdateDomainDataGrant(context.Context, *UpdateDomainDataGrantRequest) (*UpdateDomainDataGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDomainDataGrant not implemented")
}
func (UnimplementedDomainDataGrantServiceServer) DeleteDomainDataGrant(context.Context, *DeleteDomainDataGrantRequest) (*DeleteDomainDataGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomainDataGrant not implemented")
}
func (UnimplementedDomainDataGrantServiceServer) QueryDomainDataGrant(context.Context, *QueryDomainDataGrantRequest) (*QueryDomainDataGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDomainDataGrant not implemented")
}
func (UnimplementedDomainDataGrantServiceServer) BatchQueryDomainDataGrant(context.Context, *BatchQueryDomainDataGrantRequest) (*BatchQueryDomainDataGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchQueryDomainDataGrant not implemented")
}
func (UnimplementedDomainDataGrantServiceServer) ListDomainDataGrant(context.Context, *ListDomainDataGrantRequest) (*ListDomainDataGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDomainDataGrant not implemented")
}
func (UnimplementedDomainDataGrantServiceServer) mustEmbedUnimplementedDomainDataGrantServiceServer() {
}

// UnsafeDomainDataGrantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomainDataGrantServiceServer will
// result in compilation errors.
type UnsafeDomainDataGrantServiceServer interface {
	mustEmbedUnimplementedDomainDataGrantServiceServer()
}

func RegisterDomainDataGrantServiceServer(s grpc.ServiceRegistrar, srv DomainDataGrantServiceServer) {
	s.RegisterService(&DomainDataGrantService_ServiceDesc, srv)
}

func _DomainDataGrantService_CreateDomainDataGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainDataGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataGrantServiceServer).CreateDomainDataGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataGrantService_CreateDomainDataGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataGrantServiceServer).CreateDomainDataGrant(ctx, req.(*CreateDomainDataGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataGrantService_UpdateDomainDataGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainDataGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataGrantServiceServer).UpdateDomainDataGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataGrantService_UpdateDomainDataGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataGrantServiceServer).UpdateDomainDataGrant(ctx, req.(*UpdateDomainDataGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataGrantService_DeleteDomainDataGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainDataGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataGrantServiceServer).DeleteDomainDataGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataGrantService_DeleteDomainDataGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataGrantServiceServer).DeleteDomainDataGrant(ctx, req.(*DeleteDomainDataGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataGrantService_QueryDomainDataGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainDataGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataGrantServiceServer).QueryDomainDataGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataGrantService_QueryDomainDataGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataGrantServiceServer).QueryDomainDataGrant(ctx, req.(*QueryDomainDataGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataGrantService_BatchQueryDomainDataGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchQueryDomainDataGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataGrantServiceServer).BatchQueryDomainDataGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataGrantService_BatchQueryDomainDataGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataGrantServiceServer).BatchQueryDomainDataGrant(ctx, req.(*BatchQueryDomainDataGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataGrantService_ListDomainDataGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainDataGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataGrantServiceServer).ListDomainDataGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataGrantService_ListDomainDataGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataGrantServiceServer).ListDomainDataGrant(ctx, req.(*ListDomainDataGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DomainDataGrantService_ServiceDesc is the grpc.ServiceDesc for DomainDataGrantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomainDataGrantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kuscia.proto.api.v1alpha1.kusciaapi.DomainDataGrantService",
	HandlerType: (*DomainDataGrantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDomainDataGrant",
			Handler:    _DomainDataGrantService_CreateDomainDataGrant_Handler,
		},
		{
			MethodName: "UpdateDomainDataGrant",
			Handler:    _DomainDataGrantService_UpdateDomainDataGrant_Handler,
		},
		{
			MethodName: "DeleteDomainDataGrant",
			Handler:    _DomainDataGrantService_DeleteDomainDataGrant_Handler,
		},
		{
			MethodName: "QueryDomainDataGrant",
			Handler:    _DomainDataGrantService_QueryDomainDataGrant_Handler,
		},
		{
			MethodName: "BatchQueryDomainDataGrant",
			Handler:    _DomainDataGrantService_BatchQueryDomainDataGrant_Handler,
		},
		{
			MethodName: "ListDomainDataGrant",
			Handler:    _DomainDataGrantService_ListDomainDataGrant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kuscia/proto/api/v1alpha1/kusciaapi/domaindatagrant.proto",
}
