// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.11
// source: kuscia/proto/api/v1alpha1/kusciaapi/domaindatasource.proto

package kusciaapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DomainDataSourceService_CreateDomainDataSource_FullMethodName     = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataSourceService/CreateDomainDataSource"
	DomainDataSourceService_QueryDomainDataSource_FullMethodName      = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataSourceService/QueryDomainDataSource"
	DomainDataSourceService_UpdateDomainDataSource_FullMethodName     = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataSourceService/UpdateDomainDataSource"
	DomainDataSourceService_DeleteDomainDataSource_FullMethodName     = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataSourceService/DeleteDomainDataSource"
	DomainDataSourceService_BatchQueryDomainDataSource_FullMethodName = "/kuscia.proto.api.v1alpha1.kusciaapi.DomainDataSourceService/BatchQueryDomainDataSource"
)

// DomainDataSourceServiceClient is the client API for DomainDataSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DomainDataSourceServiceClient interface {
	CreateDomainDataSource(ctx context.Context, in *CreateDomainDataSourceRequest, opts ...grpc.CallOption) (*CreateDomainDataSourceResponse, error)
	QueryDomainDataSource(ctx context.Context, in *QueryDomainDataSourceRequest, opts ...grpc.CallOption) (*QueryDomainDataSourceResponse, error)
	UpdateDomainDataSource(ctx context.Context, in *UpdateDomainDataSourceRequest, opts ...grpc.CallOption) (*UpdateDomainDataSourceResponse, error)
	DeleteDomainDataSource(ctx context.Context, in *DeleteDomainDataSourceRequest, opts ...grpc.CallOption) (*DeleteDomainDataSourceResponse, error)
	BatchQueryDomainDataSource(ctx context.Context, in *BatchQueryDomainDataSourceRequest, opts ...grpc.CallOption) (*BatchQueryDomainDataSourceResponse, error)
}

type domainDataSourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDomainDataSourceServiceClient(cc grpc.ClientConnInterface) DomainDataSourceServiceClient {
	return &domainDataSourceServiceClient{cc}
}

func (c *domainDataSourceServiceClient) CreateDomainDataSource(ctx context.Context, in *CreateDomainDataSourceRequest, opts ...grpc.CallOption) (*CreateDomainDataSourceResponse, error) {
	out := new(CreateDomainDataSourceResponse)
	err := c.cc.Invoke(ctx, DomainDataSourceService_CreateDomainDataSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataSourceServiceClient) QueryDomainDataSource(ctx context.Context, in *QueryDomainDataSourceRequest, opts ...grpc.CallOption) (*QueryDomainDataSourceResponse, error) {
	out := new(QueryDomainDataSourceResponse)
	err := c.cc.Invoke(ctx, DomainDataSourceService_QueryDomainDataSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataSourceServiceClient) UpdateDomainDataSource(ctx context.Context, in *UpdateDomainDataSourceRequest, opts ...grpc.CallOption) (*UpdateDomainDataSourceResponse, error) {
	out := new(UpdateDomainDataSourceResponse)
	err := c.cc.Invoke(ctx, DomainDataSourceService_UpdateDomainDataSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataSourceServiceClient) DeleteDomainDataSource(ctx context.Context, in *DeleteDomainDataSourceRequest, opts ...grpc.CallOption) (*DeleteDomainDataSourceResponse, error) {
	out := new(DeleteDomainDataSourceResponse)
	err := c.cc.Invoke(ctx, DomainDataSourceService_DeleteDomainDataSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *domainDataSourceServiceClient) BatchQueryDomainDataSource(ctx context.Context, in *BatchQueryDomainDataSourceRequest, opts ...grpc.CallOption) (*BatchQueryDomainDataSourceResponse, error) {
	out := new(BatchQueryDomainDataSourceResponse)
	err := c.cc.Invoke(ctx, DomainDataSourceService_BatchQueryDomainDataSource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainDataSourceServiceServer is the server API for DomainDataSourceService service.
// All implementations must embed UnimplementedDomainDataSourceServiceServer
// for forward compatibility
type DomainDataSourceServiceServer interface {
	CreateDomainDataSource(context.Context, *CreateDomainDataSourceRequest) (*CreateDomainDataSourceResponse, error)
	QueryDomainDataSource(context.Context, *QueryDomainDataSourceRequest) (*QueryDomainDataSourceResponse, error)
	UpdateDomainDataSource(context.Context, *UpdateDomainDataSourceRequest) (*UpdateDomainDataSourceResponse, error)
	DeleteDomainDataSource(context.Context, *DeleteDomainDataSourceRequest) (*DeleteDomainDataSourceResponse, error)
	BatchQueryDomainDataSource(context.Context, *BatchQueryDomainDataSourceRequest) (*BatchQueryDomainDataSourceResponse, error)
	mustEmbedUnimplementedDomainDataSourceServiceServer()
}

// UnimplementedDomainDataSourceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDomainDataSourceServiceServer struct {
}

func (UnimplementedDomainDataSourceServiceServer) CreateDomainDataSource(context.Context, *CreateDomainDataSourceRequest) (*CreateDomainDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDomainDataSource not implemented")
}
func (UnimplementedDomainDataSourceServiceServer) QueryDomainDataSource(context.Context, *QueryDomainDataSourceRequest) (*QueryDomainDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDomainDataSource not implemented")
}
func (UnimplementedDomainDataSourceServiceServer) UpdateDomainDataSource(context.Context, *UpdateDomainDataSourceRequest) (*UpdateDomainDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDomainDataSource not implemented")
}
func (UnimplementedDomainDataSourceServiceServer) DeleteDomainDataSource(context.Context, *DeleteDomainDataSourceRequest) (*DeleteDomainDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomainDataSource not implemented")
}
func (UnimplementedDomainDataSourceServiceServer) BatchQueryDomainDataSource(context.Context, *BatchQueryDomainDataSourceRequest) (*BatchQueryDomainDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchQueryDomainDataSource not implemented")
}
func (UnimplementedDomainDataSourceServiceServer) mustEmbedUnimplementedDomainDataSourceServiceServer() {
}

// UnsafeDomainDataSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomainDataSourceServiceServer will
// result in compilation errors.
type UnsafeDomainDataSourceServiceServer interface {
	mustEmbedUnimplementedDomainDataSourceServiceServer()
}

func RegisterDomainDataSourceServiceServer(s grpc.ServiceRegistrar, srv DomainDataSourceServiceServer) {
	s.RegisterService(&DomainDataSourceService_ServiceDesc, srv)
}

func _DomainDataSourceService_CreateDomainDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataSourceServiceServer).CreateDomainDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataSourceService_CreateDomainDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataSourceServiceServer).CreateDomainDataSource(ctx, req.(*CreateDomainDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataSourceService_QueryDomainDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDomainDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataSourceServiceServer).QueryDomainDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataSourceService_QueryDomainDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataSourceServiceServer).QueryDomainDataSource(ctx, req.(*QueryDomainDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataSourceService_UpdateDomainDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataSourceServiceServer).UpdateDomainDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataSourceService_UpdateDomainDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataSourceServiceServer).UpdateDomainDataSource(ctx, req.(*UpdateDomainDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataSourceService_DeleteDomainDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataSourceServiceServer).DeleteDomainDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataSourceService_DeleteDomainDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataSourceServiceServer).DeleteDomainDataSource(ctx, req.(*DeleteDomainDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DomainDataSourceService_BatchQueryDomainDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchQueryDomainDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainDataSourceServiceServer).BatchQueryDomainDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainDataSourceService_BatchQueryDomainDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainDataSourceServiceServer).BatchQueryDomainDataSource(ctx, req.(*BatchQueryDomainDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DomainDataSourceService_ServiceDesc is the grpc.ServiceDesc for DomainDataSourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomainDataSourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kuscia.proto.api.v1alpha1.kusciaapi.DomainDataSourceService",
	HandlerType: (*DomainDataSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDomainDataSource",
			Handler:    _DomainDataSourceService_CreateDomainDataSource_Handler,
		},
		{
			MethodName: "QueryDomainDataSource",
			Handler:    _DomainDataSourceService_QueryDomainDataSource_Handler,
		},
		{
			MethodName: "UpdateDomainDataSource",
			Handler:    _DomainDataSourceService_UpdateDomainDataSource_Handler,
		},
		{
			MethodName: "DeleteDomainDataSource",
			Handler:    _DomainDataSourceService_DeleteDomainDataSource_Handler,
		},
		{
			MethodName: "BatchQueryDomainDataSource",
			Handler:    _DomainDataSourceService_BatchQueryDomainDataSource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kuscia/proto/api/v1alpha1/kusciaapi/domaindatasource.proto",
}
