#
# Copyright 2025 Ant Group Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: kuscia.secretflow/v1alpha1
kind: DomainData
metadata:
  name: DomainDataxxxx
  namespace: alice-xxxx
  annotations:
    originDomain: bob-xxxx
    originName: domaindata-bobxxx
  labels:
    from: manual
spec:
  uri: local://ab/c/alice_lr.csv
  type: table
  datasource: xxxxxxxxxxxxxxxxxxx
  attributes:
    rows: 10000
  partitions:
    type: path
    fields:
      - type: string
        name: date
        comment: yyyymmdd
  columns:
    - type: string
      name: userid
      comment: id of user
    - type: string
      name: x1
    - type: string
      name: x2
    - type: string
      name: x3
    - type: string
      name: x4
