# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kuscia/proto/api/v1alpha1/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&kuscia/proto/api/v1alpha1/common.proto\x12\x19kuscia.proto.api.v1alpha1\x1a\x19google/protobuf/any.proto\"\x9a\x01\n\rRequestHeader\x12S\n\x0e\x63ustom_headers\x18\x01 \x03(\x0b\x32;.kuscia.proto.api.v1alpha1.RequestHeader.CustomHeadersEntry\x1a\x34\n\x12\x43ustomHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x14.google.protobuf.AnyBQ\n\x1eorg.secretflow.v1alpha1.commonZ/github.com/secretflow/kuscia/proto/api/v1alpha1b\x06proto3')



_REQUESTHEADER = DESCRIPTOR.message_types_by_name['RequestHeader']
_REQUESTHEADER_CUSTOMHEADERSENTRY = _REQUESTHEADER.nested_types_by_name['CustomHeadersEntry']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
RequestHeader = _reflection.GeneratedProtocolMessageType('RequestHeader', (_message.Message,), {

  'CustomHeadersEntry' : _reflection.GeneratedProtocolMessageType('CustomHeadersEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUESTHEADER_CUSTOMHEADERSENTRY,
    '__module__' : 'kuscia.proto.api.v1alpha1.common_pb2'
    # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.RequestHeader.CustomHeadersEntry)
    })
  ,
  'DESCRIPTOR' : _REQUESTHEADER,
  '__module__' : 'kuscia.proto.api.v1alpha1.common_pb2'
  # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.RequestHeader)
  })
_sym_db.RegisterMessage(RequestHeader)
_sym_db.RegisterMessage(RequestHeader.CustomHeadersEntry)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'kuscia.proto.api.v1alpha1.common_pb2'
  # @@protoc_insertion_point(class_scope:kuscia.proto.api.v1alpha1.Status)
  })
_sym_db.RegisterMessage(Status)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036org.secretflow.v1alpha1.commonZ/github.com/secretflow/kuscia/proto/api/v1alpha1'
  _REQUESTHEADER_CUSTOMHEADERSENTRY._options = None
  _REQUESTHEADER_CUSTOMHEADERSENTRY._serialized_options = b'8\001'
  _REQUESTHEADER._serialized_start=97
  _REQUESTHEADER._serialized_end=251
  _REQUESTHEADER_CUSTOMHEADERSENTRY._serialized_start=199
  _REQUESTHEADER_CUSTOMHEADERSENTRY._serialized_end=251
  _STATUS._serialized_start=253
  _STATUS._serialized_end=331
# @@protoc_insertion_point(module_scope)
