# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kuscia.proto.api.v1alpha1.kusciaapi import job_pb2 as kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2


class JobServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/CreateJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CreateJobResponse.FromString,
                )
        self.QueryJob = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/QueryJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.QueryJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.QueryJobResponse.FromString,
                )
        self.BatchQueryJobStatus = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/BatchQueryJobStatus',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.BatchQueryJobStatusRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.BatchQueryJobStatusResponse.FromString,
                )
        self.StopJob = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/StopJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.StopJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.StopJobResponse.FromString,
                )
        self.RestartJob = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/RestartJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.RestartJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.RestartJobResponse.FromString,
                )
        self.SuspendJob = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/SuspendJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.SuspendJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.SuspendJobResponse.FromString,
                )
        self.CancelJob = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/CancelJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CancelJobResponse.FromString,
                )
        self.DeleteJob = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/DeleteJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.DeleteJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.DeleteJobResponse.FromString,
                )
        self.WatchJob = channel.unary_stream(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/WatchJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.WatchJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.WatchJobEventResponse.FromString,
                )
        self.ApproveJob = channel.unary_unary(
                '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/ApproveJob',
                request_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.ApproveJobRequest.SerializeToString,
                response_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.ApproveJobResponse.FromString,
                )


class JobServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchQueryJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CreateJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CreateJobResponse.SerializeToString,
            ),
            'QueryJob': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.QueryJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.QueryJobResponse.SerializeToString,
            ),
            'BatchQueryJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchQueryJobStatus,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.BatchQueryJobStatusRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.BatchQueryJobStatusResponse.SerializeToString,
            ),
            'StopJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StopJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.StopJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.StopJobResponse.SerializeToString,
            ),
            'RestartJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.RestartJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.RestartJobResponse.SerializeToString,
            ),
            'SuspendJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.SuspendJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.SuspendJobResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CancelJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CancelJobResponse.SerializeToString,
            ),
            'DeleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.DeleteJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.DeleteJobResponse.SerializeToString,
            ),
            'WatchJob': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.WatchJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.WatchJobEventResponse.SerializeToString,
            ),
            'ApproveJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveJob,
                    request_deserializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.ApproveJobRequest.FromString,
                    response_serializer=kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.ApproveJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuscia.proto.api.v1alpha1.kusciaapi.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/CreateJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CreateJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CreateJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/QueryJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.QueryJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.QueryJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchQueryJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/BatchQueryJobStatus',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.BatchQueryJobStatusRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.BatchQueryJobStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/StopJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.StopJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.StopJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestartJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/RestartJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.RestartJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.RestartJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SuspendJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/SuspendJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.SuspendJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.SuspendJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/CancelJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CancelJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.CancelJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/DeleteJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.DeleteJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.DeleteJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/WatchJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.WatchJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.WatchJobEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApproveJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kuscia.proto.api.v1alpha1.kusciaapi.JobService/ApproveJob',
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.ApproveJobRequest.SerializeToString,
            kuscia_dot_proto_dot_api_dot_v1alpha1_dot_kusciaapi_dot_job__pb2.ApproveJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
