// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/secretflow/kuscia/pkg/crd/apis/kuscia/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDataTables implements DataTableInterface
type FakeDataTables struct {
	Fake *FakeKusciaV1alpha1
	ns   string
}

var datatablesResource = schema.GroupVersionResource{Group: "kuscia.secretflow", Version: "v1alpha1", Resource: "datatables"}

var datatablesKind = schema.GroupVersionKind{Group: "kuscia.secretflow", Version: "v1alpha1", Kind: "DataTable"}

// Get takes name of the dataTable, and returns the corresponding dataTable object, and an error if there is any.
func (c *FakeDataTables) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(datatablesResource, c.ns, name), &v1alpha1.DataTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataTable), err
}

// List takes label and field selectors, and returns the list of DataTables that match those selectors.
func (c *FakeDataTables) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataTableList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(datatablesResource, datatablesKind, c.ns, opts), &v1alpha1.DataTableList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DataTableList{ListMeta: obj.(*v1alpha1.DataTableList).ListMeta}
	for _, item := range obj.(*v1alpha1.DataTableList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataTables.
func (c *FakeDataTables) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(datatablesResource, c.ns, opts))

}

// Create takes the representation of a dataTable and creates it.  Returns the server's representation of the dataTable, and an error, if there is any.
func (c *FakeDataTables) Create(ctx context.Context, dataTable *v1alpha1.DataTable, opts v1.CreateOptions) (result *v1alpha1.DataTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(datatablesResource, c.ns, dataTable), &v1alpha1.DataTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataTable), err
}

// Update takes the representation of a dataTable and updates it. Returns the server's representation of the dataTable, and an error, if there is any.
func (c *FakeDataTables) Update(ctx context.Context, dataTable *v1alpha1.DataTable, opts v1.UpdateOptions) (result *v1alpha1.DataTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(datatablesResource, c.ns, dataTable), &v1alpha1.DataTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataTable), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDataTables) UpdateStatus(ctx context.Context, dataTable *v1alpha1.DataTable, opts v1.UpdateOptions) (*v1alpha1.DataTable, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(datatablesResource, "status", c.ns, dataTable), &v1alpha1.DataTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataTable), err
}

// Delete takes name of the dataTable and deletes it. Returns an error if one occurs.
func (c *FakeDataTables) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(datatablesResource, c.ns, name, opts), &v1alpha1.DataTable{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataTables) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(datatablesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DataTableList{})
	return err
}

// Patch applies the patch and returns the patched dataTable.
func (c *FakeDataTables) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataTable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datatablesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DataTable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataTable), err
}
