// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/secretflow/kuscia/pkg/crd/apis/kuscia/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKusciaDeployments implements KusciaDeploymentInterface
type FakeKusciaDeployments struct {
	Fake *FakeKusciaV1alpha1
}

var kusciadeploymentsResource = schema.GroupVersionResource{Group: "kuscia.secretflow", Version: "v1alpha1", Resource: "kusciadeployments"}

var kusciadeploymentsKind = schema.GroupVersionKind{Group: "kuscia.secretflow", Version: "v1alpha1", Kind: "KusciaDeployment"}

// Get takes name of the kusciaDeployment, and returns the corresponding kusciaDeployment object, and an error if there is any.
func (c *FakeKusciaDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KusciaDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(kusciadeploymentsResource, name), &v1alpha1.KusciaDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaDeployment), err
}

// List takes label and field selectors, and returns the list of KusciaDeployments that match those selectors.
func (c *FakeKusciaDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KusciaDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(kusciadeploymentsResource, kusciadeploymentsKind, opts), &v1alpha1.KusciaDeploymentList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KusciaDeploymentList{ListMeta: obj.(*v1alpha1.KusciaDeploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.KusciaDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kusciaDeployments.
func (c *FakeKusciaDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(kusciadeploymentsResource, opts))
}

// Create takes the representation of a kusciaDeployment and creates it.  Returns the server's representation of the kusciaDeployment, and an error, if there is any.
func (c *FakeKusciaDeployments) Create(ctx context.Context, kusciaDeployment *v1alpha1.KusciaDeployment, opts v1.CreateOptions) (result *v1alpha1.KusciaDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(kusciadeploymentsResource, kusciaDeployment), &v1alpha1.KusciaDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaDeployment), err
}

// Update takes the representation of a kusciaDeployment and updates it. Returns the server's representation of the kusciaDeployment, and an error, if there is any.
func (c *FakeKusciaDeployments) Update(ctx context.Context, kusciaDeployment *v1alpha1.KusciaDeployment, opts v1.UpdateOptions) (result *v1alpha1.KusciaDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(kusciadeploymentsResource, kusciaDeployment), &v1alpha1.KusciaDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKusciaDeployments) UpdateStatus(ctx context.Context, kusciaDeployment *v1alpha1.KusciaDeployment, opts v1.UpdateOptions) (*v1alpha1.KusciaDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(kusciadeploymentsResource, "status", kusciaDeployment), &v1alpha1.KusciaDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaDeployment), err
}

// Delete takes name of the kusciaDeployment and deletes it. Returns an error if one occurs.
func (c *FakeKusciaDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(kusciadeploymentsResource, name, opts), &v1alpha1.KusciaDeployment{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKusciaDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(kusciadeploymentsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KusciaDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched kusciaDeployment.
func (c *FakeKusciaDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KusciaDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(kusciadeploymentsResource, name, pt, data, subresources...), &v1alpha1.KusciaDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaDeployment), err
}
