// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/secretflow/kuscia/pkg/crd/apis/kuscia/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKusciaTasks implements KusciaTaskInterface
type FakeKusciaTasks struct {
	Fake *FakeKusciaV1alpha1
	ns   string
}

var kusciatasksResource = schema.GroupVersionResource{Group: "kuscia.secretflow", Version: "v1alpha1", Resource: "kusciatasks"}

var kusciatasksKind = schema.GroupVersionKind{Group: "kuscia.secretflow", Version: "v1alpha1", Kind: "KusciaTask"}

// Get takes name of the kusciaTask, and returns the corresponding kusciaTask object, and an error if there is any.
func (c *FakeKusciaTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KusciaTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kusciatasksResource, c.ns, name), &v1alpha1.KusciaTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaTask), err
}

// List takes label and field selectors, and returns the list of KusciaTasks that match those selectors.
func (c *FakeKusciaTasks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KusciaTaskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kusciatasksResource, kusciatasksKind, c.ns, opts), &v1alpha1.KusciaTaskList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KusciaTaskList{ListMeta: obj.(*v1alpha1.KusciaTaskList).ListMeta}
	for _, item := range obj.(*v1alpha1.KusciaTaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kusciaTasks.
func (c *FakeKusciaTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kusciatasksResource, c.ns, opts))

}

// Create takes the representation of a kusciaTask and creates it.  Returns the server's representation of the kusciaTask, and an error, if there is any.
func (c *FakeKusciaTasks) Create(ctx context.Context, kusciaTask *v1alpha1.KusciaTask, opts v1.CreateOptions) (result *v1alpha1.KusciaTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kusciatasksResource, c.ns, kusciaTask), &v1alpha1.KusciaTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaTask), err
}

// Update takes the representation of a kusciaTask and updates it. Returns the server's representation of the kusciaTask, and an error, if there is any.
func (c *FakeKusciaTasks) Update(ctx context.Context, kusciaTask *v1alpha1.KusciaTask, opts v1.UpdateOptions) (result *v1alpha1.KusciaTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kusciatasksResource, c.ns, kusciaTask), &v1alpha1.KusciaTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaTask), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKusciaTasks) UpdateStatus(ctx context.Context, kusciaTask *v1alpha1.KusciaTask, opts v1.UpdateOptions) (*v1alpha1.KusciaTask, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kusciatasksResource, "status", c.ns, kusciaTask), &v1alpha1.KusciaTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaTask), err
}

// Delete takes name of the kusciaTask and deletes it. Returns an error if one occurs.
func (c *FakeKusciaTasks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kusciatasksResource, c.ns, name, opts), &v1alpha1.KusciaTask{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKusciaTasks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kusciatasksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KusciaTaskList{})
	return err
}

// Patch applies the patch and returns the patched kusciaTask.
func (c *FakeKusciaTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KusciaTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kusciatasksResource, c.ns, name, pt, data, subresources...), &v1alpha1.KusciaTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KusciaTask), err
}
