// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/secretflow/kuscia/pkg/crd/apis/kuscia/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDomainRoutes implements DomainRouteInterface
type FakeDomainRoutes struct {
	Fake *FakeKusciaV1alpha1
	ns   string
}

var domainroutesResource = schema.GroupVersionResource{Group: "kuscia.secretflow", Version: "v1alpha1", Resource: "domainroutes"}

var domainroutesKind = schema.GroupVersionKind{Group: "kuscia.secretflow", Version: "v1alpha1", Kind: "DomainRoute"}

// Get takes name of the domainRoute, and returns the corresponding domainRoute object, and an error if there is any.
func (c *FakeDomainRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DomainRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(domainroutesResource, c.ns, name), &v1alpha1.DomainRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRoute), err
}

// List takes label and field selectors, and returns the list of DomainRoutes that match those selectors.
func (c *FakeDomainRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DomainRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(domainroutesResource, domainroutesKind, c.ns, opts), &v1alpha1.DomainRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DomainRouteList{ListMeta: obj.(*v1alpha1.DomainRouteList).ListMeta}
	for _, item := range obj.(*v1alpha1.DomainRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested domainRoutes.
func (c *FakeDomainRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(domainroutesResource, c.ns, opts))

}

// Create takes the representation of a domainRoute and creates it.  Returns the server's representation of the domainRoute, and an error, if there is any.
func (c *FakeDomainRoutes) Create(ctx context.Context, domainRoute *v1alpha1.DomainRoute, opts v1.CreateOptions) (result *v1alpha1.DomainRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(domainroutesResource, c.ns, domainRoute), &v1alpha1.DomainRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRoute), err
}

// Update takes the representation of a domainRoute and updates it. Returns the server's representation of the domainRoute, and an error, if there is any.
func (c *FakeDomainRoutes) Update(ctx context.Context, domainRoute *v1alpha1.DomainRoute, opts v1.UpdateOptions) (result *v1alpha1.DomainRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(domainroutesResource, c.ns, domainRoute), &v1alpha1.DomainRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDomainRoutes) UpdateStatus(ctx context.Context, domainRoute *v1alpha1.DomainRoute, opts v1.UpdateOptions) (*v1alpha1.DomainRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(domainroutesResource, "status", c.ns, domainRoute), &v1alpha1.DomainRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRoute), err
}

// Delete takes name of the domainRoute and deletes it. Returns an error if one occurs.
func (c *FakeDomainRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(domainroutesResource, c.ns, name, opts), &v1alpha1.DomainRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDomainRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(domainroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DomainRouteList{})
	return err
}

// Patch applies the patch and returns the patched domainRoute.
func (c *FakeDomainRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DomainRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(domainroutesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DomainRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainRoute), err
}
