apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runk-role
  namespace: autonomy-alice
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runk-rolebinding
  namespace: autonomy-alice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runk-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: autonomy-alice
