// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/secretflow/kuscia/pkg/crd/apis/kuscia/v1alpha1"
	scheme "github.com/secretflow/kuscia/pkg/crd/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DomainAppImagesGetter has a method to return a DomainAppImageInterface.
// A group's client should implement this interface.
type DomainAppImagesGetter interface {
	DomainAppImages(namespace string) DomainAppImageInterface
}

// DomainAppImageInterface has methods to work with DomainAppImage resources.
type DomainAppImageInterface interface {
	Create(ctx context.Context, domainAppImage *v1alpha1.DomainAppImage, opts v1.CreateOptions) (*v1alpha1.DomainAppImage, error)
	Update(ctx context.Context, domainAppImage *v1alpha1.DomainAppImage, opts v1.UpdateOptions) (*v1alpha1.DomainAppImage, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DomainAppImage, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DomainAppImageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DomainAppImage, err error)
	DomainAppImageExpansion
}

// domainAppImages implements DomainAppImageInterface
type domainAppImages struct {
	client rest.Interface
	ns     string
}

// newDomainAppImages returns a DomainAppImages
func newDomainAppImages(c *KusciaV1alpha1Client, namespace string) *domainAppImages {
	return &domainAppImages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the domainAppImage, and returns the corresponding domainAppImage object, and an error if there is any.
func (c *domainAppImages) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DomainAppImage, err error) {
	result = &v1alpha1.DomainAppImage{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("domainappimages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DomainAppImages that match those selectors.
func (c *domainAppImages) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DomainAppImageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DomainAppImageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("domainappimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested domainAppImages.
func (c *domainAppImages) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("domainappimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a domainAppImage and creates it.  Returns the server's representation of the domainAppImage, and an error, if there is any.
func (c *domainAppImages) Create(ctx context.Context, domainAppImage *v1alpha1.DomainAppImage, opts v1.CreateOptions) (result *v1alpha1.DomainAppImage, err error) {
	result = &v1alpha1.DomainAppImage{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("domainappimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(domainAppImage).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a domainAppImage and updates it. Returns the server's representation of the domainAppImage, and an error, if there is any.
func (c *domainAppImages) Update(ctx context.Context, domainAppImage *v1alpha1.DomainAppImage, opts v1.UpdateOptions) (result *v1alpha1.DomainAppImage, err error) {
	result = &v1alpha1.DomainAppImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("domainappimages").
		Name(domainAppImage.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(domainAppImage).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the domainAppImage and deletes it. Returns an error if one occurs.
func (c *domainAppImages) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("domainappimages").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *domainAppImages) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("domainappimages").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched domainAppImage.
func (c *domainAppImages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DomainAppImage, err error) {
	result = &v1alpha1.DomainAppImage{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("domainappimages").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
