// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/secretflow/kuscia/pkg/crd/apis/kuscia/v1alpha1"
	scheme "github.com/secretflow/kuscia/pkg/crd/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KusciaTaskSummariesGetter has a method to return a KusciaTaskSummaryInterface.
// A group's client should implement this interface.
type KusciaTaskSummariesGetter interface {
	KusciaTaskSummaries(namespace string) KusciaTaskSummaryInterface
}

// KusciaTaskSummaryInterface has methods to work with KusciaTaskSummary resources.
type KusciaTaskSummaryInterface interface {
	Create(ctx context.Context, kusciaTaskSummary *v1alpha1.KusciaTaskSummary, opts v1.CreateOptions) (*v1alpha1.KusciaTaskSummary, error)
	Update(ctx context.Context, kusciaTaskSummary *v1alpha1.KusciaTaskSummary, opts v1.UpdateOptions) (*v1alpha1.KusciaTaskSummary, error)
	UpdateStatus(ctx context.Context, kusciaTaskSummary *v1alpha1.KusciaTaskSummary, opts v1.UpdateOptions) (*v1alpha1.KusciaTaskSummary, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.KusciaTaskSummary, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.KusciaTaskSummaryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KusciaTaskSummary, err error)
	KusciaTaskSummaryExpansion
}

// kusciaTaskSummaries implements KusciaTaskSummaryInterface
type kusciaTaskSummaries struct {
	client rest.Interface
	ns     string
}

// newKusciaTaskSummaries returns a KusciaTaskSummaries
func newKusciaTaskSummaries(c *KusciaV1alpha1Client, namespace string) *kusciaTaskSummaries {
	return &kusciaTaskSummaries{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kusciaTaskSummary, and returns the corresponding kusciaTaskSummary object, and an error if there is any.
func (c *kusciaTaskSummaries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KusciaTaskSummary, err error) {
	result = &v1alpha1.KusciaTaskSummary{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KusciaTaskSummaries that match those selectors.
func (c *kusciaTaskSummaries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KusciaTaskSummaryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KusciaTaskSummaryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kusciaTaskSummaries.
func (c *kusciaTaskSummaries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kusciaTaskSummary and creates it.  Returns the server's representation of the kusciaTaskSummary, and an error, if there is any.
func (c *kusciaTaskSummaries) Create(ctx context.Context, kusciaTaskSummary *v1alpha1.KusciaTaskSummary, opts v1.CreateOptions) (result *v1alpha1.KusciaTaskSummary, err error) {
	result = &v1alpha1.KusciaTaskSummary{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kusciaTaskSummary).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kusciaTaskSummary and updates it. Returns the server's representation of the kusciaTaskSummary, and an error, if there is any.
func (c *kusciaTaskSummaries) Update(ctx context.Context, kusciaTaskSummary *v1alpha1.KusciaTaskSummary, opts v1.UpdateOptions) (result *v1alpha1.KusciaTaskSummary, err error) {
	result = &v1alpha1.KusciaTaskSummary{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		Name(kusciaTaskSummary.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kusciaTaskSummary).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *kusciaTaskSummaries) UpdateStatus(ctx context.Context, kusciaTaskSummary *v1alpha1.KusciaTaskSummary, opts v1.UpdateOptions) (result *v1alpha1.KusciaTaskSummary, err error) {
	result = &v1alpha1.KusciaTaskSummary{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		Name(kusciaTaskSummary.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kusciaTaskSummary).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kusciaTaskSummary and deletes it. Returns an error if one occurs.
func (c *kusciaTaskSummaries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kusciaTaskSummaries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kusciaTaskSummary.
func (c *kusciaTaskSummaries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KusciaTaskSummary, err error) {
	result = &v1alpha1.KusciaTaskSummary{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kusciatasksummaries").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
