apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuscia-master
  namespace: kuscia-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuscia-master
  template:
    metadata:
      labels:
        app: kuscia-master
    spec:
      dnsPolicy: None # Explicitly set dnsPolicy to None to fully manage DNS settings
      dnsConfig:
        nameservers:
          - 127.0.0.1
      containers:
        - command:
            - tini
            - --
            - kuscia
            - start
            - -c
            - etc/conf/kuscia.yaml
          image: secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:0.11.0b0
          imagePullPolicy: Always
          name: master
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/kuscia/etc/conf/kuscia.yaml
              name: kuscia-master-conf
              subPath: kuscia.yaml
            - mountPath: /home/kuscia/var/tmp/resolv.conf
              name: kuscia-master-conf
              subPath: resolv.conf
          workingDir: /home/kuscia
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              add:
                - NET_BIND_SERVICE
      automountServiceAccountToken: true
      volumes:
        - configMap:
            defaultMode: 420
            name: kuscia-master-cm
          name: kuscia-master-conf