apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: patch.yaml
namespace: {{.NAMESPACE}} # modify here to your own domain
replacements:
  - source:
      kind: Deployment
      name: monitor
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Deployment
          name: monitor
        fieldPaths:
          - spec.template.spec.nodeSelector.[kuscia.secretflow/namespace]