apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: alice
spec:
  template:
    spec:
      serviceAccountName: default
      tolerations:
      - effect: NoSchedule
        key: kuscia.secretflow/agent
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
      schedulerName: kuscia-scheduler
      nodeSelector:
        kuscia.secretflow/namespace: alice