// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/secretflow/kuscia/pkg/crd/apis/kuscia/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KusciaTaskSummaryLister helps list KusciaTaskSummaries.
// All objects returned here must be treated as read-only.
type KusciaTaskSummaryLister interface {
	// List lists all KusciaTaskSummaries in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KusciaTaskSummary, err error)
	// KusciaTaskSummaries returns an object that can list and get KusciaTaskSummaries.
	KusciaTaskSummaries(namespace string) KusciaTaskSummaryNamespaceLister
	KusciaTaskSummaryListerExpansion
}

// kusciaTaskSummaryLister implements the KusciaTaskSummaryLister interface.
type kusciaTaskSummaryLister struct {
	indexer cache.Indexer
}

// NewKusciaTaskSummaryLister returns a new KusciaTaskSummaryLister.
func NewKusciaTaskSummaryLister(indexer cache.Indexer) KusciaTaskSummaryLister {
	return &kusciaTaskSummaryLister{indexer: indexer}
}

// List lists all KusciaTaskSummaries in the indexer.
func (s *kusciaTaskSummaryLister) List(selector labels.Selector) (ret []*v1alpha1.KusciaTaskSummary, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KusciaTaskSummary))
	})
	return ret, err
}

// KusciaTaskSummaries returns an object that can list and get KusciaTaskSummaries.
func (s *kusciaTaskSummaryLister) KusciaTaskSummaries(namespace string) KusciaTaskSummaryNamespaceLister {
	return kusciaTaskSummaryNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KusciaTaskSummaryNamespaceLister helps list and get KusciaTaskSummaries.
// All objects returned here must be treated as read-only.
type KusciaTaskSummaryNamespaceLister interface {
	// List lists all KusciaTaskSummaries in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KusciaTaskSummary, err error)
	// Get retrieves the KusciaTaskSummary from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.KusciaTaskSummary, error)
	KusciaTaskSummaryNamespaceListerExpansion
}

// kusciaTaskSummaryNamespaceLister implements the KusciaTaskSummaryNamespaceLister
// interface.
type kusciaTaskSummaryNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KusciaTaskSummaries in the indexer for a given namespace.
func (s kusciaTaskSummaryNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.KusciaTaskSummary, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KusciaTaskSummary))
	})
	return ret, err
}

// Get retrieves the KusciaTaskSummary from the indexer for a given namespace and name.
func (s kusciaTaskSummaryNamespaceLister) Get(name string) (*v1alpha1.KusciaTaskSummary, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("kusciatasksummary"), name)
	}
	return obj.(*v1alpha1.KusciaTaskSummary), nil
}
