// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/secretflow/kuscia/pkg/crd/apis/kuscia/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KusciaBetaDeploymentLister helps list KusciaBetaDeployments.
// All objects returned here must be treated as read-only.
type KusciaBetaDeploymentLister interface {
	// List lists all KusciaBetaDeployments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KusciaBetaDeployment, err error)
	// KusciaBetaDeployments returns an object that can list and get KusciaBetaDeployments.
	KusciaBetaDeployments(namespace string) KusciaBetaDeploymentNamespaceLister
	KusciaBetaDeploymentListerExpansion
}

// kusciaBetaDeploymentLister implements the KusciaBetaDeploymentLister interface.
type kusciaBetaDeploymentLister struct {
	indexer cache.Indexer
}

// NewKusciaBetaDeploymentLister returns a new KusciaBetaDeploymentLister.
func NewKusciaBetaDeploymentLister(indexer cache.Indexer) KusciaBetaDeploymentLister {
	return &kusciaBetaDeploymentLister{indexer: indexer}
}

// List lists all KusciaBetaDeployments in the indexer.
func (s *kusciaBetaDeploymentLister) List(selector labels.Selector) (ret []*v1alpha1.KusciaBetaDeployment, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KusciaBetaDeployment))
	})
	return ret, err
}

// KusciaBetaDeployments returns an object that can list and get KusciaBetaDeployments.
func (s *kusciaBetaDeploymentLister) KusciaBetaDeployments(namespace string) KusciaBetaDeploymentNamespaceLister {
	return kusciaBetaDeploymentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KusciaBetaDeploymentNamespaceLister helps list and get KusciaBetaDeployments.
// All objects returned here must be treated as read-only.
type KusciaBetaDeploymentNamespaceLister interface {
	// List lists all KusciaBetaDeployments in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KusciaBetaDeployment, err error)
	// Get retrieves the KusciaBetaDeployment from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.KusciaBetaDeployment, error)
	KusciaBetaDeploymentNamespaceListerExpansion
}

// kusciaBetaDeploymentNamespaceLister implements the KusciaBetaDeploymentNamespaceLister
// interface.
type kusciaBetaDeploymentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KusciaBetaDeployments in the indexer for a given namespace.
func (s kusciaBetaDeploymentNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.KusciaBetaDeployment, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KusciaBetaDeployment))
	})
	return ret, err
}

// Get retrieves the KusciaBetaDeployment from the indexer for a given namespace and name.
func (s kusciaBetaDeploymentNamespaceLister) Get(name string) (*v1alpha1.KusciaBetaDeployment, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("kusciabetadeployment"), name)
	}
	return obj.(*v1alpha1.KusciaBetaDeployment), nil
}
