apiVersion: v1
kind: Service
metadata:
  name: kuscia-lite-alice
  namespace: lite-alice
spec:
  selector:
    app: kuscia-lite-alice
  type: ClusterIP
  ports:
    - name: envoy
      port: 1080
      protocol: TCP
      targetPort: 1080
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: kusciaapi
      port: 8082
      protocol: TCP
      targetPort: 8082