# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kuscia/proto/api/v1alpha1/appconfig/app_config.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4kuscia/proto/api/v1alpha1/appconfig/app_config.proto\x12#kuscia.proto.api.v1alpha1.appconfig\"/\n\x07Service\x12\x11\n\tport_name\x18\x01 \x01(\t\x12\x11\n\tendpoints\x18\x02 \x03(\t\"c\n\x05Party\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12>\n\x08services\x18\x03 \x03(\x0b\x32,.kuscia.proto.api.v1alpha1.appconfig.Service\"\x7f\n\rClusterDefine\x12;\n\x07parties\x18\x01 \x03(\x0b\x32*.kuscia.proto.api.v1alpha1.appconfig.Party\x12\x16\n\x0eself_party_idx\x18\x02 \x01(\x05\x12\x19\n\x11self_endpoint_idx\x18\x03 \x01(\x05\"C\n\x04Port\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\r\n\x05scope\x18\x03 \x01(\t\x12\x10\n\x08protocol\x18\x04 \x01(\t\"J\n\x0e\x41llocatedPorts\x12\x38\n\x05ports\x18\x01 \x03(\x0b\x32).kuscia.proto.api.v1alpha1.appconfig.PortB^\n!com.secretflow.v1alpha1.appconfigZ9github.com/secretflow/kuscia/proto/api/v1alpha1/appconfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kuscia.proto.api.v1alpha1.appconfig.app_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.secretflow.v1alpha1.appconfigZ9github.com/secretflow/kuscia/proto/api/v1alpha1/appconfig'
  _globals['_SERVICE']._serialized_start=93
  _globals['_SERVICE']._serialized_end=140
  _globals['_PARTY']._serialized_start=142
  _globals['_PARTY']._serialized_end=241
  _globals['_CLUSTERDEFINE']._serialized_start=243
  _globals['_CLUSTERDEFINE']._serialized_end=370
  _globals['_PORT']._serialized_start=372
  _globals['_PORT']._serialized_end=439
  _globals['_ALLOCATEDPORTS']._serialized_start=441
  _globals['_ALLOCATEDPORTS']._serialized_end=515
# @@protoc_insertion_point(module_scope)
