apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuscia
rules:
  - apiGroups:
      - kuscia.secretflow
    resources:
      - "*"
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
