apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuscia
rules:
  - apiGroups:
      - kuscia.secretflow
    resources:
      - "*"
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch